name: 'social_media_rollup_integration_tests'
version: '0.3.0'
profile: 'integration_tests'
config-version: 2

vars:
  twitter_organic_source:
    twitter_organic_schema: social_media_rollup_integration_tests
    twitter_organic_account_history_identifer: "twitter_organic_account_history_data"
    twitter_organic_organic_tweet_report_identifer: "twitter_organic_organic_tweet_report_data"
    twitter_organic_tweet_identifer: "twitter_organic_tweet_data"
    twitter_organic_twitter_user_history_identifer: "twitter_organic_twitter_user_history_data"
  linkedin_pages_source:
    linkedin_pages_schema: social_media_rollup_integration_tests
    linkedin_pages_organization_identifier: "linkedin_pages_organization_data"
    linkedin_pages_organization_ugc_post_identifier: "linkedin_pages_organization_ugc_post_data"
    linkedin_pages_share_statistic_identifier: "linkedin_pages_share_statistic_data"
    linkedin_pages_post_content_identifier: "linkedin_pages_post_content_data"
    linkedin_pages_ugc_post_history_identifier: "linkedin_pages_ugc_post_history_data"
    linkedin_pages_ugc_post_share_statistic_identifier: "linkedin_pages_ugc_post_share_statistic_data"
  instagram_business_source:
    instagram_business_schema: social_media_rollup_integration_tests
    instagram_business_media_history_identifier: "instagram_business_media_history_data"
    instagram_business_media_insights_identifier: "instagram_business_media_insights_data"
    instagram_business_user_history_identifier: "instagram_business_user_history_data"
  facebook_pages_source:
    facebook_pages_schema: social_media_rollup_integration_tests
    facebook_pages_daily_page_metrics_total_identifier: "facebook_pages_daily_page_metrics_total_data"
    facebook_pages_lifetime_post_metrics_total_identifier: "facebook_pages_lifetime_post_metrics_total_data"
    facebook_pages_page_identifier: "facebook_pages_page_data"
    facebook_pages_post_history_identifier: "facebook_pages_post_history_data"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

models: 
  social_media_reporting:
    +materialized: table
  twitter_organic_source:
    +materialized: table
  facebook_pages_source:
    +materialized: table
  linkedin_pages_source:
    +materialized: table
  instagram_business_source:
    +materialized: table
    
seeds:
  social_media_rollup_integration_tests:
    twitter_organic_tweet_data:
      +column_types: 
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    twitter_organic_organic_tweet_report_data:
      +column_types:
        organic_tweet_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"

    linkedin_pages_ugc_post_share_statistic_data:
      +column_types:
        ugc_post_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        
    instagram_business_media_history_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}" 
        ig_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        user_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}" 
        carousel_album_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}" 
    instagram_business_media_insights_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}" 
    instagram_business_user_history_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}" 
        ig_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"

    facebook_pages_post_history_data:
      +column_types:
        id: "{{ 'string' if target.type in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
        promotable_id: "{{ 'string' if target.type in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
        page_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    facebook_pages_lifetime_post_metrics_total_data:
      +column_types:
        post_id: "{{ 'string' if target.type in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
    facebook_pages_page_data:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    facebook_pages_daily_page_metrics_total_data:
      +column_types:
        page_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"