name: 'social_media_rollup_integration_tests'
version: '0.1.0'
profile: 'integration_tests'
config-version: 2

vars:
  account_history: "{{ ref('twitter_organic_account_history_data') }}"
  organic_tweet_report: "{{ ref('twitter_organic_organic_tweet_report_data') }}"
  tweet: "{{ ref('twitter_organic_tweet_data') }}"
  twitter_user_history: "{{ ref('twitter_organic_twitter_user_history_data') }}"
  share_statistic: "{{ ref('linkedin_pages_share_statistic_data') }}"
  ugc_post_share_statistic: "{{ ref('linkedin_pages_ugc_post_share_statistic_data') }}"
  ugc_post_history: "{{ ref('linkedin_pages_ugc_post_history_data') }}"
  ugc_post_share_content_media: "{{ ref('linkedin_pages_ugc_post_share_content_media_data') }}"
  organization: "{{ ref('linkedin_pages_organization_data') }}"
  organization_ugc_post: "{{ ref('linkedin_pages_organization_ugc_post_data') }}"
  media_history: "{{ ref('instagram_business_media_history_data') }}"
  media_insights: "{{ ref('instagram_business_media_insights_data') }}"
  user_history: "{{ ref('instagram_business_user_history_data') }}"
  post_history: "{{ ref('facebook_pages_post_history_data') }}"
  page: "{{ ref('facebook_pages_page_data') }}"
  lifetime_post_metrics_total: "{{ ref('facebook_pages_lifetime_post_metrics_total_data') }}"
  daily_page_metrics_total: "{{ ref('facebook_pages_daily_page_metrics_total_data') }}"
  
models:
  dbt_social_media_reporting:
    +materialized: table

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
    
seeds:
  social_media_rollup_integration_tests:
    twitter_organic_tweet_data:
      +column_types: 
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    twitter_organic_organic_tweet_report_data:
      +column_types:
        organic_tweet_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"

    linkedin_pages_ugc_post_share_statistic_data:
      +column_types:
        ugc_post_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        
    instagram_business_media_history_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}" 
        ig_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        user_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}" 
        carousel_album_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}" 
    instagram_business_media_insights_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}" 
    instagram_business_user_history_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}" 
        ig_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"

    facebook_pages_post_history_data:
      +column_types:
        id: "{{ 'string' if target.type in ['bigquery','spark'] else 'varchar' }}"
        promotable_id: "{{ 'string' if target.type in ['bigquery','spark'] else 'varchar' }}"
        page_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    facebook_pages_lifetime_post_metrics_total_data:
      +column_types:
        post_id: "{{ 'string' if target.type in ['bigquery','spark'] else 'varchar' }}"
    facebook_pages_page_data:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    facebook_pages_daily_page_metrics_total_data:
      +column_types:
        page_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
